### PR TITLE
Change Agency id and service id to integers

### PR DESCRIPTION
**Pull request by avilaton**
Tables containing agecy_id and service_id have been updated to integers. All underlying data were also updated.

### CODE REVIEW

**Comment by fabid** [comment]
Hi,
Any reason to switch the ids to integer? The GTFS reference by Google does not state such constraint, and I did come across GTFS feeds where ids were not integers.

**Comment by avilaton** [comment]
This was a choice I had to make to simplify CRUD on these objects but you are right, it is not mentioned in the spec and restricts the types of feeds one could possibly import later on. The same holds for route_id, trip_id, and so on. Having integers there means we can have them be managed by the DB and forget about certain things.
The restriction might be removed later on, time permitting.

**Comment by fabid** [comment]
Thanks for the reply. I may take a look and see what I can do.

**Comment by avilaton** [comment]
Thanks to you for taking an interest in it.
At the moment a user will POST to /api/agency/ an object and an ID will be created for it.

**Pull request merged**
